import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import '@/styles/global.css';

import { Inter } from "next/font/google";
import { PrimeReactProvider } from 'primereact/api';
import { ThemeProvider } from '@/context/ThemeContext';

import ClientOnly from '@/components/ClientOnly';
import OverlaySpinner from '@/components/OverlaySpinner';

import WindowEventListener from '../listeners/WindowEventListener';

if (typeof window === 'undefined') {
  require('localstorage-polyfill');
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <WindowEventListener />
        <PrimeReactProvider>
          <ClientOnly>
            <ThemeProvider>
              { children }
              <OverlaySpinner />
            </ThemeProvider>
          </ClientOnly>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
